tag @s remove power0
tag @s remove power1
tag @s remove power2
tag @s remove power3
tag @s remove power4
tag @s remove power5
tag @s remove power6
tag @s remove power7
tag @s remove power8
tag @s remove power9
tag @s remove power10
tag @s remove power11
tag @s remove power12
tag @s remove power13
tag @s remove power14
tag @s remove power15
tag @s remove power16
tag @s remove power17
tag @s remove power18
tag @s remove power19
tag @s remove power20
tag @s remove power21
tag @s remove power22
tag @s remove power23
tag @s remove power24
tag @s remove power25
tag @s remove power26
tag @s remove power27
tag @s remove power28
tag @s remove power29
tag @s remove power30
tag @s remove power31
tag @s remove power32
tag @s remove power33
tag @s remove power34
tag @s remove power35
tag @s remove power36
tag @s remove power37
tag @s remove power38
tag @s remove power39
tag @s remove power40
tag @s remove power41
tag @s remove power42
tag @s remove power43
tag @s remove power44
tag @s remove power45
tag @s remove power46
tag @s remove power47
tag @s remove power48
tag @s remove power49
tag @s remove power50
tag @s remove power51
tag @s remove power52
tag @s remove power53
tag @s remove power54
tag @s remove power55
tag @s remove power56
tag @s remove power57
tag @s remove power58
tag @s remove power59
tag @s remove power60
tag @s remove power61
tag @s remove power62
tag @s remove power63
tag @s remove power64
tag @s remove power65
tag @s remove power66
tag @s remove power67
tag @s remove power68
tag @s remove power69
tag @s remove power70
tag @s remove power71
tag @s remove power72
tag @s remove power73
tag @s remove power74
tag @s remove power75
tag @s remove power76
tag @s remove power77
tag @s remove power78
tag @s remove power79
tag @s remove power80
tag @s remove power81
tag @s remove power82
tag @s remove power83
tag @s remove power84
tag @s remove power85
tag @s remove power86
tag @s remove power87
tag @s remove power88
tag @s remove power89
tag @s remove power90
tag @s remove power91
tag @s remove power92
tag @s remove power93
tag @s remove power94
tag @s remove power95
tag @s remove power96
tag @s remove power97
tag @s remove power98
tag @s remove power99
tag @s remove power100
tag @s remove power101
tag @s remove power102
tag @s remove power103
tag @s remove power104
tag @s remove power105
tag @s remove power106
tag @s remove power107
tag @s remove power108
tag @s remove power109
tag @s remove power110
tag @s remove power111
tag @s remove power112
tag @s remove power113
tag @s remove power114
tag @s remove power115
tag @s remove power116
tag @s remove power117
tag @s remove power118
tag @s remove power119
tag @s remove power120
tag @s remove power121
tag @s remove power122
tag @s remove power123
tag @s remove power124
tag @s remove power125
tag @s remove power126
tag @s remove power127
tag @s remove power128
tag @s remove power129
tag @s remove power130
tag @s remove power131
tag @s remove power132
tag @s remove power133
tag @s remove power134
tag @s remove power135
tag @s remove power136
tag @s remove power137
tag @s remove power138
tag @s remove power139
tag @s remove power140
tag @s remove power141
tag @s remove power142
tag @s remove power143
tag @s remove power144
tag @s remove power145
tag @s remove power146
tag @s remove power147
tag @s remove power148
tag @s remove power149
tag @s remove power150
